service: demo 
provider:
  name: aws
  runtime: nodejs10.x

functions:
  createInvoice:
    handler: src/functions/v1/createInvoice.handler
    events:
      - http:
          path: v1/invoice
          method: post
          cors: true

plugins:
  - serverless-offline        
