service: demo 
provider:
  name: aws
  runtime: nodejs10.x

functions:
  createInvoiceV1:
    handler: src/v1/functions/createInvoice.handler
    events:
      - http:
          path: v1/invoice
          method: post
          cors: true
  createInvoiceV2:
    handler: src/v2/functions/createInvoice.handler
    events:
      - http:
          path: v2/invoice
          method: post
          cors: true          

plugins:
  - serverless-offline        
